package com.example.savemoney.InitList

import com.example.savemoney.R

class ListOfIcon {


    fun list():ArrayList<Int>
    {
        var listIcon = ArrayList<Int>()

        listIcon.add(R.drawable.ambulance)
        listIcon.add(R.drawable.arayeshgah)
        listIcon.add(R.drawable.ashpaz)
        listIcon.add(R.drawable.baby)
        listIcon.add(R.drawable.badkonak)
        listIcon.add(R.drawable.banki)
        listIcon.add(R.drawable.banna)
        listIcon.add(R.drawable.barbary)
        listIcon.add(R.drawable.boshghab)
        listIcon.add(R.drawable.darman)
        listIcon.add(R.drawable.dastmozd)
        listIcon.add(R.drawable.dastmozd1)
        listIcon.add(R.drawable.doctor)
        listIcon.add(R.drawable.doorbin)
        listIcon.add(R.drawable.dorbinfilmbardary)
        listIcon.add(R.drawable.ejare_mostaghellat)
        listIcon.add(R.drawable.fenjonghahveh)
        listIcon.add(R.drawable.froosh_amval)
        listIcon.add(R.drawable.froosh_amval1)
        listIcon.add(R.drawable.ghelyoon)
        listIcon.add(R.drawable.ghobooz)
        listIcon.add(R.drawable.ghori)
        listIcon.add(R.drawable.gitarist)
        listIcon.add(R.drawable.goldangol)
        listIcon.add(R.drawable.gorbaeh)
        listIcon.add(R.drawable.hadaya)
        listIcon.add(R.drawable.havapeyma)
        listIcon.add(R.drawable.hoghoogh)
        listIcon.add(R.drawable.kart_banki)
        listIcon.add(R.drawable.kalej)
        listIcon.add(R.drawable.kart_banki)
        listIcon.add(R.drawable.kerem)
        listIcon.add(R.drawable.keshavarz)
        listIcon.add(R.drawable.ketab)
        listIcon.add(R.drawable.khayat)
        listIcon.add(R.drawable.khoshkshooyii)
        listIcon.add(R.drawable.khyriye)
        listIcon.add(R.drawable.kiseberenj)
        listIcon.add(R.drawable.kifpol)
        listIcon.add(R.drawable.kise_pol)
        listIcon.add(R.drawable.kore_zamin)
        listIcon.add(R.drawable.lavazem_arayesh)
        listIcon.add(R.drawable.lavazem_tahrir)
        listIcon.add(R.drawable.list)
        listIcon.add(R.drawable.mahitabeh)
        listIcon.add(R.drawable.mashin)
        listIcon.add(R.drawable.maskan)
        listIcon.add(R.drawable.mask)
        listIcon.add(R.drawable.mavadproteeni)
        listIcon.add(R.drawable.mivevasabzi)
        listIcon.add(R.drawable.moaalem)
        listIcon.add(R.drawable.mohandes)
        listIcon.add(R.drawable.nemodargheymat)
        listIcon.add(R.drawable.nezafatchi)
        listIcon.add(R.drawable.parastar)
        listIcon.add(R.drawable.rafto_amad)
        listIcon.add(R.drawable.pas_andaz)
        listIcon.add(R.drawable.paziraee)
        listIcon.add(R.drawable.peykmotori)
        listIcon.add(R.drawable.poshak)
        listIcon.add(R.drawable.restoran)
        listIcon.add(R.drawable.sag)
        listIcon.add(R.drawable.sakhtwmansazi)
        listIcon.add(R.drawable.sandoogh_post)
        listIcon.add(R.drawable.sayer_daramad)
        listIcon.add(R.drawable.sayer_hazine)
        listIcon.add(R.drawable.sefaresh)
        listIcon.add(R.drawable.sefaresh2)
        listIcon.add(R.drawable.shahrebazi)
        listIcon.add(R.drawable.sinama)
        listIcon.add(R.drawable.soodbanki)
        listIcon.add(R.drawable.stakhar)
        listIcon.add(R.drawable.supery)
        listIcon.add(R.drawable.taamir_lavazem)
        listIcon.add(R.drawable.taghvim_moosighi)
        listIcon.add(R.drawable.tarazo)
        listIcon.add(R.drawable.tooti)
        listIcon.add(R.drawable.traktor)
        listIcon.add(R.drawable.vam)
        listIcon.add(R.drawable.varzesh)
        listIcon.add(R.drawable.vasayelnezafat)
        listIcon.add(R.drawable.vilcher)
        listIcon.add(R.drawable.yaraneh)
        listIcon.add(R.drawable.yoga)
        listIcon.add(R.drawable.zan_hameleh)

        return listIcon
    }
}